# file: Dockerfile.webview
FROM python:3.13-slim

WORKDIR /app

COPY . .
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 96

CMD ["gunicorn", "qr_mobile:application", "--bind", "0.0.0.0:96"]
