
services:
  glasses:
    build: 
      context: .
      dockerfile: Dockerfile.glasses
    ports:
      - "81:81"
    volumes:
      - ./src:/app

  webview:
    build:
      context: .
      dockerfile: Dockerfile.webview
    ports:
      - "96:96"
    env_file:
      - mentra.env
    volumes:
      - ./contacts_management/templates:/app/contacts_management/templates
      - ./contacts_management/static:/app/contacts_management/static
    depends_on:
      - glasses
    restart: unless-stopped    

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token {CLOUDFLARED_TOKEN}
    env_file:
      - mentra.env